In [28]:
import requests
from datetime import datetime

# Define the GraphQL endpoint
endpoint = 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3'

# Define the GraphQL query
query = '''
query poolDayDatas($startTime: Int!,$endTime: Int!, $skip: Int!, $address: Bytes!) {
  poolDayDatas(
    first: 1000
    skip: $skip
    where: {pool: $address, date_gt: $startTime}
    orderBy: date
    orderDirection: asc
    subgraphError: allow
  ) {
    date
    volumeUSD
    tvlUSD
    feesUSD
    pool {
      feeTier
      __typename
    }
    __typename
  }
}
'''

# Get the current timestamp and the desired timeframe
start_timestamp = 1684395515
end_timestamp = 1688543783

# Set the query variables
variables = {
    "startTime": start_timestamp,
    "endTime": end_timestamp,
    "skip": 0,
    "address": "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
}

# Define the GraphQL request payload
payload = {
    "query": query,
    "variables": variables
}

# Send the GraphQL request
response = requests.post(endpoint, json=payload)

# Initialize an empty list
data = []

# Process the query response
if response.status_code == 200:
    data_response = response.json().get('data')
    print(data_response)
    if data_response:
        poolDayDatas = data_response.get('poolDayDatas')
        for dayData in poolDayDatas:
            if dayData['date'] >= start_timestamp and dayData['date'] <= end_timestamp:
                timestamp = dayData['date']
                fees = float(dayData['feesUSD'])
                data.append({'Timestamp': timestamp, 'Fees': fees})

# Convert the list of dictionaries to a dataframe
df = pd.DataFrame(data)

# Save the dataframe to a CSV file
df.to_csv('ETHUSDC_fees.csv', index=False)

df

{'poolDayDatas': [{'date': 1684454400, 'volumeUSD': '156975037.9115792594827849369142208', 'tvlUSD': '438406376.1842893958223574984906597', 'feesUSD': '78487.5189557896297413924684571092', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1684540800, 'volumeUSD': '106100592.0894317960958000194531066', 'tvlUSD': '438230055.8422697218553633638841867', 'feesUSD': '53050.29604471589804790000972655286', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1684627200, 'volumeUSD': '118507381.7928599717881359775372745', 'tvlUSD': '435179611.0130747191849792179673433', 'feesUSD': '59253.69089642998589406798876863798', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1684713600, 'volumeUSD': '143098920.4934782125545690282661096', 'tvlUSD': '439103276.9846713266016371947613595', 'feesUSD': '71549.46024673910627728451413305393', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1684800000, 'volumeUSD': '151451276.5868561458275180715205171', 'tvlUSD': '440573112.3367443270875498232819377', 'feesUSD': '75725.63829342807291375903576025854', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1684886400, 'volumeUSD': '195422966.3688794440784166136591286', 'tvlUSD': '432612641.8809263124573442562095932', 'feesUSD': '97711.48318443972203920830682956601', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1684972800, 'volumeUSD': '143080671.4126206949328267889417463', 'tvlUSD': '431696791.0907911279761973809262625', 'feesUSD': '71540.33570631034746641339447087325', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685059200, 'volumeUSD': '123315087.3531342379760362320906152', 'tvlUSD': '433359022.1881555552104431050170211', 'feesUSD': '61657.54367656711898801811604530727', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685145600, 'volumeUSD': '64513276.07628688314223774160237479', 'tvlUSD': '427026473.9416022342674684828187319', 'feesUSD': '32256.63803814344157111887080118724', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685232000, 'volumeUSD': '218565628.8358290841859747595533896', 'tvlUSD': '444954070.1473467213273023798308759', 'feesUSD': '109282.8144179145420929873797766941', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685318400, 'volumeUSD': '207406778.0079172318760223616224965', 'tvlUSD': '446262955.069654040154011192438675', 'feesUSD': '103703.3890039586159380111808112497', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685404800, 'volumeUSD': '224702214.1301622508880025058638582', 'tvlUSD': '447708242.7864036363393789325555898', 'feesUSD': '112351.1070650811254440012529319299', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685491200, 'volumeUSD': '225435478.486737337964197603494425', 'tvlUSD': '441759330.1213317518446539111995371', 'feesUSD': '112717.7392433686689820988017472132', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685577600, 'volumeUSD': '183544442.192936047936416290239941', 'tvlUSD': '437529502.7553252914730700280926116', 'feesUSD': '91772.2210964680239682081451199705', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685664000, 'volumeUSD': '196085231.2548907665165334065511081', 'tvlUSD': '460354336.4180478785063972401353139', 'feesUSD': '98042.61562744538325826670327555393', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685750400, 'volumeUSD': '96205000.04028690040701419021683051', 'tvlUSD': '460179743.9158597663122029296562022', 'feesUSD': '48102.50002014345020350709510841546', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685836800, 'volumeUSD': '108605785.1546696054036326982339876', 'tvlUSD': '461288982.1991788407190695459187013', 'feesUSD': '54302.89257733480270181634911699378', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1685923200, 'volumeUSD': '379610992.8623894171816656167820908', 'tvlUSD': '453515199.6093142909762696241271969', 'feesUSD': '189805.4964311947085908328083910439', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686009600, 'volumeUSD': '334008446.7298931010960051857946965', 'tvlUSD': '467794400.5588222304925438390828037', 'feesUSD': '167004.223364946550548002592897347', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686096000, 'volumeUSD': '296593710.5895915459137951137117678', 'tvlUSD': '461090868.7205308764683185386791982', 'feesUSD': '148296.8552947957729568975568558833', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686182400, 'volumeUSD': '141813398.3952542823382166580337944', 'tvlUSD': '464096253.4213476613449103336582412', 'feesUSD': '70906.69919762714116910832901689779', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686268800, 'volumeUSD': '128995584.504335468797345300942891', 'tvlUSD': '464380331.4227017670049058712520517', 'feesUSD': '64497.7922521677343986726504714457', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686355200, 'volumeUSD': '518252141.3683635397485859347462543', 'tvlUSD': '429806352.116992919428461758863794', 'feesUSD': '259126.0706841817698742929673731254', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686441600, 'volumeUSD': '132187582.615282051224046020468309', 'tvlUSD': '438197749.4187395952698143620929341', 'feesUSD': '66093.79130764102561202301023415535', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686528000, 'volumeUSD': '219692421.4039235195302049587314435', 'tvlUSD': '436819274.3604466380249382123172657', 'feesUSD': '109846.2107019617597651024793657216', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686614400, 'volumeUSD': '238365942.891563073773192163833656', 'tvlUSD': '448704112.2028490937981524440848154', 'feesUSD': '119182.9714457815368865960819168277', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686700800, 'volumeUSD': '263426131.3727404047282649438906298', 'tvlUSD': '419478768.0523418293404273495590093', 'feesUSD': '131713.0656863702023641324719453141', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686787200, 'volumeUSD': '213616081.3536728442947378657379122', 'tvlUSD': '424485593.7359565533553676556186844', 'feesUSD': '106808.0406768364221473689328689587', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686873600, 'volumeUSD': '143646868.7837916152863623197486947', 'tvlUSD': '433572482.6186793486228884739599514', 'feesUSD': '71823.4343918958076431811598743478', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1686960000, 'volumeUSD': '113509883.2018543638933907816022353', 'tvlUSD': '416835243.7507036082018311310403643', 'feesUSD': '56754.94160092718194669539080111749', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687046400, 'volumeUSD': '80928628.32347648029213592200812251', 'tvlUSD': '416700091.0548915289002984360238854', 'feesUSD': '40464.3141617382401460679610040613', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687132800, 'volumeUSD': '175474111.2361911965703379017970277', 'tvlUSD': '417819588.7306309323360816058004846', 'feesUSD': '87737.05561809559828516895089851503', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687219200, 'volumeUSD': '259392708.3363343984202080052897398', 'tvlUSD': '425349373.8855329087908099773835332', 'feesUSD': '129696.3541681671992101040026448686', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687305600, 'volumeUSD': '497512509.9142899487066067364361613', 'tvlUSD': '432671317.3088498952369694614599739', 'feesUSD': '248756.2549571449743533033682180822', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687392000, 'volumeUSD': '311825770.9573760525772289119940516', 'tvlUSD': '437083367.4216334313796143604640191', 'feesUSD': '155912.8854786880262886144559970238', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687478400, 'volumeUSD': '343611549.6364858094695129929199608', 'tvlUSD': '438042407.3101285502214132739105576', 'feesUSD': '171805.7748182429047347564964599809', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687564800, 'volumeUSD': '152875012.4122300721751524253184247', 'tvlUSD': '435520382.3176303303968319940557265', 'feesUSD': '76437.50620611503608757621265921197', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687651200, 'volumeUSD': '233356330.9470855632554579612121715', 'tvlUSD': '438736887.9128858876075476542589987', 'feesUSD': '116678.1654735427816277289806060845', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687737600, 'volumeUSD': '342186303.4920209181988637511736553', 'tvlUSD': '434295865.2648840857784335699369439', 'feesUSD': '171093.1517460104590994318755868298', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687824000, 'volumeUSD': '246227729.6043183058000080205267032', 'tvlUSD': '439776810.8399413722484738917949965', 'feesUSD': '123113.864802159152900004010263353', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687910400, 'volumeUSD': '243854300.2172699309700878620317344', 'tvlUSD': '434091816.7695353755051644641422238', 'feesUSD': '121927.1501086349654850439310158666', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1687996800, 'volumeUSD': '201783529.5099921343058245431218487', 'tvlUSD': '435514510.4246276948992219896650765', 'feesUSD': '100891.7647549960671529122715609242', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1688083200, 'volumeUSD': '533698945.5001479010699874333650794', 'tvlUSD': '443479030.9459918937285717567193973', 'feesUSD': '266849.4727500739505349937166825393', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1688169600, 'volumeUSD': '219641756.3763647736383932312302585', 'tvlUSD': '456559853.6230038524155869492813337', 'feesUSD': '109820.87818818238681919661561513', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1688256000, 'volumeUSD': '223062416.8663179107819293416092063', 'tvlUSD': '459760178.6338139513100630119101172', 'feesUSD': '111531.208433158955390964670804604', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1688342400, 'volumeUSD': '316661240.8373505615143628738460774', 'tvlUSD': '461900717.1252164963712903068794762', 'feesUSD': '158330.6204186752807571814369230381', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1688428800, 'volumeUSD': '220421373.2755584024166479350567443', 'tvlUSD': '470343158.1100655267119187736507009', 'feesUSD': '110210.6866377792012083239675283732', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1688515200, 'volumeUSD': '280542892.8653180203787605095851492', 'tvlUSD': '474212789.9717628236808598013432758', 'feesUSD': '140271.4464326590101893802547925769', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1688601600, 'volumeUSD': '325483491.3022725705621249451158526', 'tvlUSD': '465293197.9778481403628143004180196', 'feesUSD': '162741.7456511362852810624725579252', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}, {'date': 1688688000, 'volumeUSD': '138473014.3035801167212876457388665', 'tvlUSD': '469008110.1170782029236561190462739', 'feesUSD': '69236.50715179005836064382286943325', 'pool': {'feeTier': '500', '__typename': 'Pool'}, '__typename': 'PoolDayData'}]}

     Timestamp           Fees
0   1684454400   78487.518956
1   1684540800   53050.296045
2   1684627200   59253.690896
3   1684713600   71549.460247
4   1684800000   75725.638293
5   1684886400   97711.483184
6   1684972800   71540.335706
7   1685059200   61657.543677
8   1685145600   32256.638038
9   1685232000  109282.814418
10  1685318400  103703.389004
11  1685404800  112351.107065
12  1685491200  112717.739243
13  1685577600   91772.221096
14  1685664000   98042.615627
15  1685750400   48102.500020
16  1685836800   54302.892577
17  1685923200  189805.496431
18  1686009600  167004.223365
19  1686096000  148296.855295
20  1686182400   70906.699198
21  1686268800   64497.792252
22  1686355200  259126.070684
23  1686441600   66093.791308
24  1686528000  109846.210702
25  1686614400  119182.971446
26  1686700800  131713.065686
27  1686787200  106808.040677
28  1686873600   71823.434392
29  1686960000   56754.941601
30  1687046400   40464.314162
31  1687132800   87737.055618
32  1687219200  129696.354168
33  1687305600  248756.254957
34  1687392000  155912.885479
35  1687478400  171805.774818
36  1687564800   76437.506206
37  1687651200  116678.165474
38  1687737600  171093.151746
39  1687824000  123113.864802
40  1687910400  121927.150109
41  1687996800  100891.764755
42  1688083200  266849.472750
43  1688169600  109820.878188
44  1688256000  111531.208433
45  1688342400  158330.620419
46  1688428800  110210.686638
47  1688515200  140271.446433

In [25]:
import requests
from datetime import datetime
import pandas as pd

# Define the GraphQL endpoint
endpoint = 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3'

# Define the GraphQL query
query = '''
query poolDayDatas($startTime: Int!,$endTime: Int!, $skip: Int!, $address: Bytes!) {
  poolDayDatas(
    first: 1000
    skip: $skip
    where: {pool: $address, date_gt: $startTime}
    orderBy: date
    orderDirection: asc
    subgraphError: allow
  ) {
    date
    volumeUSD
    tvlUSD
    feesUSD
    pool {
      feeTier
      __typename
    }
    __typename
  }
}
'''

# Get the current timestamp and the desired timeframe
start_timestamp = 1680438347
end_timestamp = 1682777999

# Set the query variables
variables = {
    "startTime": start_timestamp,
    "endTime": end_timestamp,
    "skip": 0,
    "address": "0xd1d5a4c0ea98971894772dcd6d2f1dc71083c44e"
}

# Define the GraphQL request payload
payload = {
    "query": query,
    "variables": variables
}

# Send the GraphQL request
response = requests.post(endpoint, json=payload)

# Initialize an empty list
data = []

# Process the query response
if response.status_code == 200:
    data_response = response.json().get('data')
    if data_response:
        poolDayDatas = data_response.get('poolDayDatas')
        for dayData in poolDayDatas:
            if dayData['date'] >= start_timestamp and dayData['date'] <= end_timestamp:
                timestamp = dayData['date']
                fees = float(dayData['feesUSD'])
                data.append({'Timestamp': timestamp, 'Fees': fees})

# Convert the list of dictionaries to a dataframe
df = pd.DataFrame(data)

# Save the dataframe to a CSV file
df.to_csv('LQTYETH_fees.csv', index=False)


df

     Timestamp          Fees
0   1680480000   4581.699968
1   1680566400   7198.335221
2   1680652800   7866.136811
3   1680739200   5503.380428
4   1680825600   2882.465583
5   1680912000   1803.380702
6   1680998400   1232.174305
7   1681084800   1584.978456
8   1681171200   1077.909860
9   1681257600   4716.525428
10  1681344000   1284.570482
11  1681430400   5697.983249
12  1681516800  11539.668795
13  1681603200   3041.350857
14  1681689600   6034.586740
15  1681776000   5353.568753
16  1681862400   6302.527523
17  1681948800   2277.372175
18  1682035200   2822.465411
19  1682121600   1073.659223
20  1682208000   1383.613946
21  1682294400    774.152175
22  1682380800   1075.187404
23  1682467200   1165.282340
24  1682553600    558.527552
25  1682640000   1805.960974
26  1682726400   1324.148298